# Generated by Django 5.2 on 2025-04-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='swift_code',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
