# Generated by Django 5.2 on 2025-04-14 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True)),
                ('bank_name', models.CharField()),
                ('country_iso_2', models.CharField()),
                ('country_name', models.CharField()),
                ('swift_code', models.CharField(unique=True)),
                ('is_headquarter', models.BooleanField()),
                ('headquarter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='api.code')),
            ],
        ),
    ]
